#!/usr/bin/env bash

if [ $# -ne 3 ]; then
    echo "Errore: <IP> <porta_iniziale> <porta_finale>"
    exit 1
fi

ip=$1
porta1=$2
porta2=$3

if ! [[ $ip =~ ^((25[0-5]|2[0-4][0-9]|1[0-9]{2}|[1-9]?[0-9])\.){3}(25[0-5]|2[0-4][0-9]|1[0-9]{2}|[1-9]?[0-9])$ ]]; then
    echo "Errore: IP non valido."
    exit 1
fi

if ! [[ $porta1 =~ ^[0-9]+$ && $porta2 =~ ^[0-9]+$ ]]; then
    echo "Errore: le porte devono essere numeri."
    exit 1
fi

if [ $porta1 -lt 1 ] || [ $porta2 -gt 65535 ] || [ $porta1 -gt $porta2 ]; then
    echo "Errore: intervallo porte non valido."
    exit 1
fi

echo
echo "========================================"
echo "             PORT SCANNER"
echo "========================================"
echo " Target : $ip"
echo " Range  : $porta1 - $porta2"
echo "========================================"
echo

aperte=0

for ((i=porta1; i<=porta2; i++))
do
        echo | nc -w 1 $ip $i &>/dev/null

        if [ $? -eq 0 ]; then
                echo " Porta $i: APERTA"                
        ((aperte++))
        fi
done
echo
echo "========================================"
echo " Scansione completata."
echo " Porte aperte trovate: $aperte"
echo "========================================"
echo