Vagrant.configure("2") do |config|
    config.vm.define "rocky1" do |config|
    config.vm.box = "generic/rocky9"
    config.vm.hostname = "rocky1"
    config.vm.network "private_network", ip: "192.168.3.10"
    config.vm.disk :disk, size: "10GB", name: "secondo_disco"

    #config.vm.provision "shell", inline: <<-SHELL
     #   dnf update -y
     #   dnf install -y podman
    #SHELL

    config.vm.provider "virtualbox" do |vb|
        vb.memory = "1024"
        vb.cpus = 1
    end
  end

  config.vm.define "rocky2" do |config|
    config.vm.box = "generic/rocky9"
    config.vm.hostname = "rocky2"
    config.vm.network "private_network", ip: "192.168.3.9"
    config.vm.disk :disk, size: "10GB", name: "secondo_disco"

    #config.vm.provision "shell", inline: <<-SHELL
     #   dnf update -y
     #   dnf install -y podman
    #SHELL

    config.vm.provider "virtualbox" do |vb|
        vb.memory = "1024"
        vb.cpus = 1
    end
  end
end

