Vagrant.configure("2") do |config|

          # Proxy-1 - FRONTEND 
  config.vm.define "Proxy-1" do |vm|
    vm.vm.box = "generic/rocky9"
    vm.vm.hostname = "Proxy-1"
    vm.vm.network "private_network", ip: "192.168.3.2"

    vm.vm.provision "shell", inline: <<-SHELL
      dnf update -y
      dnf install -y haproxy

      mkdir -p /etc/ssl/mycerts
      openssl req -new -x509 -days 365 -nodes -subj "/C=IT/ST=RM/L=Roma/O=Lab/CN=Proxy-1" -out /etc/ssl/mycerts/server.crt -keyout /etc/ssl/mycerts/server.key
      cat /etc/ssl/mycerts/server.crt /etc/ssl/mycerts/server.key > /etc/ssl/mycerts/proxy.pem
      cat <<EOF > /etc/haproxy/haproxy.cfg
      global
       daemon
       log /dev/log local0

      defaults
       mode http
       log global
       timeout connect 5s
       timeout client 30s
       timeout server 30s

      frontend https_front
       bind *:443 ssl crt /etc/ssl/mycerts/proxy.pem

       default_backend siti_backend

      backend siti_backend
       balance first

       server web1 192.168.3.3:80 check fall 3 rise 2 
       server web2 192.168.3.4:80 check backup fall 3 rise 2 
EOF
      systemctl restart haproxy
      firewall-cmd --permanent --add-port=443/tcp
      firewall-cmd --reload

      SHELL
  

    vm.vm.provider "virtualbox" do |vb|
      vb.memory = "1024"
      vb.cpus = 1
    end
  end

          # Web-1 - BACKEND SITO 1  
  config.vm.define "Web-1" do |vm|
    vm.vm.box = "generic/rocky9"
    vm.vm.hostname = "Web-1"
    vm.vm.network "private_network", ip: "192.168.3.3"

    vm.vm.provision "shell", inline: <<-SHELL
      dnf update -y
      dnf install -y httpd
      echo "Benvenuto su Web-1" > /var/www/html/index.html
      systemctl restart httpd
      firewall-cmd --permanent --add-port=80/tcp
      firewall-cmd --reload 

      SHELL
      

    vm.vm.provider "virtualbox" do |vb|
      vb.memory = "1024"
      vb.cpus = 1
    end
  end

          # Web-2 - BACKEND SITO 2  
  config.vm.define "Web-2" do |vm|
    vm.vm.box = "generic/rocky9"
    vm.vm.hostname = "Web-2"
    vm.vm.network "private_network", ip: "192.168.3.4"

    vm.vm.provision "shell", inline: <<-SHELL
      dnf update -y
      dnf install -y httpd
      echo "Benvenuto su Web-2" > /var/www/html/index.html
      systemctl restart httpd 
      firewall-cmd --permanent --add-port=80/tcp
      firewall-cmd --reload

      SHELL
      

    vm.vm.provider "virtualbox" do |vb|
      vb.memory = "1024"
      vb.cpus = 1
    end
  end

end