---
- hosts: ubuntu
  become: true

  tasks:
    - name: Prendere lo script con curl
      get_url:
        url: https://get.docker.com
        dest: /root/get-docker.sh
        mode: '0755'

    - name: Avvia script per scaricare docker
      command: /root/get-docker.sh

    - name: Crea container del gioco
      community.docker.docker_container:
        name: "{{ item }}"
        image: alpine:latest
        command: sleep infity
        state: stopped
      loop:
        - contadino
        - lupo
        - capra
        - cavolo

    - name: Aggiungi utente vagrant al gruppo docker
      user:
        name: vagrant
        groups: docker
        append: yes

    - name: Copia script indovinello
      copy:
        src: Script
        dest: /home/vagrant/indovinello
        mode: '0755'