Vagrant.configure("2") do |config|

          # ubuntu1  
  config.vm.define "ubuntu1" do |vm|
    vm.vm.box = "ubuntu/jammy64"
    vm.vm.hostname = "ubuntu1"
    vm.vm.network "private_network", ip: "192.168.3.2"
    vm.vm.synced_folder "./condivisa", "/condivisa"
    vm.vm.provision "shell", inline: <<-SHELL
    sudo -u vagrant ssh-keygen -t ed25519 -f /home/vagrant/.ssh/id_ed25519 -N ""
    sudo -u vagrant cp /home/vagrant/.ssh/id_ed25519.pub /condivisa/id_ed25519.pub
    SHELL
    
      vm.vm.provider "virtualbox" do |vb|
      vb.memory = "1024"
      vb.cpus = 1
    end
  end

          # ubuntu2
  config.vm.define "ubuntu2" do |vm|
    vm.vm.box = "ubuntu/jammy64"
    vm.vm.hostname = "ubuntu2"
    vm.vm.network "private_network", ip: "192.168.3.3"
    vm.vm.synced_folder "./condivisa", "/condivisa"
    vm.vm.provision "shell", inline: <<-SHELL
    sudo -u vagrant cat /condivisa/id_ed25519.pub >> /home/vagrant/.ssh/authorized_keys
    SHELL

    vm.vm.provider "virtualbox" do |vb|
      vb.memory = "1024"
      vb.cpus = 1
    end
    
    vm.vm.provision "ansible" do |ansible|
    ansible.playbook = "playbook.yaml"
    ansible.limit = "all"
    end
  end

end